rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-2.1.1
  - ruby-head
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
